### ISSUE TITLE
[Q/FR] Sync labels based on a config file within another repository

### ISSUE THREAD

**Issue by h1dden-da3m0n** [EndBug/label-sync#1]
Greetings there,

I am curious if it where at al passible to allow the configuration of this action to work with both `source-repo` and `config-file` to have one 'configuration repository to rule them all'?
This behaviour is already somewhat possible to realize, however it is limited to only one configuration by having this action run in one repo on a `config-file` to sync its labels and then any 'dependent' repos to clone those via the `source-repo` config.

Theoretically it should be possible to realize since GitHub's API allows for [direct file access](https://docs.github.com/en/rest/reference/repos#get-repository-content) and I am interested in looking into adding this functionality to this Action if it wasn't already planed.

So the question/feature-request boils down to: have you planed/are you planing of adding this functionality, or would you accept a PR adding such?

Thank you for your work so far!

**Comment by EndBug** [comment]
Feature has been merged and published in `v2.0.0` (`v2`, `latest`)
Thanks again for your contribution! ❤️
