### ISSUE TITLE
Allow hash-prefix in color codes

### ISSUE THREAD

**Issue by armsnyder** [EndBug/label-sync#116]
The upstream gitlab-label-sync package supports the hash-prefix [when it is run as a binary](https://github.com/Financial-Times/github-label-sync/blob/991da8d302b82c428c5890ba8b6493fad650a424/bin/github-label-sync.js#L140), but not as a library.

Could you detect and strip the `#` prefix while parsing config? It allows us to visualize colors with [IDE plugins](https://marketplace.visualstudio.com/items?itemName=naumovs.color-highlight).

<img width="412" alt="Screen Shot 2022-01-31 at 6 23 11 PM" src="https://user-images.githubusercontent.com/9969202/151904277-87d2453e-28c6-44c3-92c7-027759164466.png">

**Comment by EndBug** [comment]
@all-contributors please add @armsnyder for their code contribution
