### ISSUE TITLE
bug: Only 30 labels are synced

### ISSUE THREAD

**Issue by MaddoScientisto** [EndBug/label-sync#162]
Tested on version 2.3.1
I tried to do a sync by specifying a source-repo to another repository which has 60 labels, the original one had 10 labels.
The action only pulled the first 30 labels and ignored the rest, as it turns out 30 is the page size in the labels page, this makes me think there's some pagination issue going on with the API that is used by the action, so it should be changed to handle pagination and grab all the tags in the source repository.

Edit: according to the documentation https://docs.github.com/en/rest/issues/labels#list-labels-for-a-repository it does seem like that the default page number is 30 and this is not handled in the script

**Comment by EndBug** [comment]
Hey @MaddoScientisto sorry for the long wait!
I've just pushed a quick fix to the `162-pagination` branch, would you like to try it?
You can just use the actions as usual but with the `EndBug/label-sync@162-pagination` ref

**Comment by MaddoScientisto** [comment]
Thank you, I'll try right away!

**Comment by MaddoScientisto** [comment]
@EndBug I just tried it but it still grabbed 30 labels, is there a parameter I have to specify?

**Comment by EndBug** [comment]
Not really, it should just work ahahaha
Can you share the logs?

**Comment by MaddoScientisto** [comment]
yes sorry I was getting to that https://gist.github.com/MaddoScientisto/937edd8d2071900e357cf7ddd1ad517a
it only said 30 labels there

**Comment by MaddoScientisto** [comment]
@EndBug works perfectly: I have all 67 labels synced

**Comment by EndBug** [comment]
Nice! I'll release the patch when my plane lands 👍🏻

**Comment by MaddoScientisto** [comment]
@EndBug did that plane land yet? I've been looking forward to that release

**Comment by EndBug** [comment]
Oh god I've completely forgot about it 😅 
I'll do this this afternoon, promise!

**Comment by EndBug** [comment]
@all-contributors please add @MaddoScientisto for their bug report
