### ISSUE TITLE
Relative `.github/` path fails

### ISSUE THREAD

**Issue by hiddeco** [EndBug/label-sync#204]
Based on the example in the `README.md`, the following workflow snippet:

```yaml
    steps:
      - uses: EndBug/label-sync@da00f2c11fdb78e4fae44adac2fdd713778ea3e8 # v2.3.2
        with:
          # Configuration file
          config-file: .github/labels.yaml
```

results in the following error:

```
Reading config file...
  🛈 Reading file...
  ##[debug]Resolved path: /home/runner/work/<repo-name>/<repo-name>/.github/labels.yaml
  ##[debug]Actual error: Error: ENOENT: no such file or directory, open '/home/runner/work/<repo-name>/<repo-name>/.github/labels.yaml'
```

**Comment by EndBug** [comment]
Hi, sorry for the confusion: if you want to use the file as a local path, you need to make sure you have checked out the repository (like with `actions/checkout`) before you run the action.
Otherwise, you can use GitHub's raw content link.

**Comment by hiddeco** [comment]
Of course, should have read the full example more carefully and spend a minute thinking 🤦🏼‍♂️
