### ISSUE TITLE
failed to sync labeles

### ISSUE THREAD

**Issue by lielran** [EndBug/label-sync#22]
1. need to add validation for more than 64 chars descriptions for labels. 
2.action failed:
```
Checking inputs...
  🛈 Checking inputs...
  ✓ Inputs are valid
Reading config file...
  🛈 Reading file...
  🛈 Parsing YAML file...
  ✓ File parsed successfully.
  🛈 Parsed config:

....
...
...

```
Syncing labels...
  Error: ✗ Error: Validation Failed

with no indication of what and why

**Comment by EndBug** [comment]
Hi, sorry if I only reply now. 
Could you post the config file you're using and the actual action run (preferably a permalink to both, instead of pasting it here)?
