### ISSUE TITLE
[Q] dependabot and octokit

### ISSUE THREAD

**Issue by h1dden-da3m0n** [EndBug/label-sync#3]
Hi again, 
this time just a couple of questions that came up while working on #1.

* Any particular reason this project does not use Dependabot to keep dependencies up to date?
* Any particular reason why you dont use [`@actions/github`](https://github.com/actions/toolkit/tree/main/packages/github) over `axios`?

I don't feel particularly strong about either of the questions, just curious :wink:

**Comment by EndBug** [comment]
No, not really, it's just that I conceived this repo as a little action that I could use for myself, and so it lacks a lot of open-source stuff that I usually add to my other projects 😅

**Comment by h1dden-da3m0n** [comment]
What do you mean, you have a licence and the code is accessible to everyone. Looks perfectly open source to me :wink: 
Fun aside, don't worry about it, I was just curious and since I rather contribute than re-invent the wheel (I was about to writ my own action that works just like yours before I found yours) I will contribute what I can.

**Comment by EndBug** [comment]
Is this issue still relevant after #2 or can it be closed?

**Comment by h1dden-da3m0n** [comment]
Well the questions where answered, so this can bow be closed :wink:
