### ISSUE TITLE
The action is not working for me.

### ISSUE THREAD

**Issue by Souvikns** [EndBug/label-sync#97]
I am getting `Error: ✗ <ParseException> Unable to parse. (line 7: '<!DOCTYPE html>')` when I run the action. I am passing URL as a config-file parameter. I think the file is following the correct format because I am not getting any error when I try to convert it to JSON. 

Here is the action URL https://github.com/Tech-Phantoms/Auth/runs/4158543894?check_suite_focus=true 

![image](https://user-images.githubusercontent.com/41781438/141013895-11be09ab-414b-4e20-b2bd-921e5a5d3959.png)

**Comment by EndBug** [comment]
You're using the URL to the GitHub web page that refers to your YAML file, instead of the API URL that gets the raw content of the file:

```none
https://raw.githubusercontent.com/Tech-Phantoms/.github/main/.github/label-list.yml
```
